version: "3.6"
services:
  gateway:
    image: nginx
    volumes:
      # - ./gateway/nginx.conf:/tmp/nginx.conf
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./gateway/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 8080:80   # API gateway
    depends_on:
      - controller
  
  controller:
    build:
      # context: .
      # Diretory with TSA sources
      context: controller
      dockerfile: Dockerfile
      # target: builder
    environment:
      - FLASK_RUN_PORT=8080
      - FLASK_ENV=development
      - FLASK_APP=app/main
      - FLASK_RUN_HOST=0.0.0.0
      # Adiciona o caminho do controller para permitir
      # importar classes que lá se encontram 
      - PYTHONPATH=$PALANTIR_HOME
      # As variáveis abaixo provêm do env-file .env 
      - DBCONFIG
      - PALANTIR_HOME
    #   - FLASK_SERVER_PORT=9091
    command: flask run
    # command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./controller/app:/code/app
    # environment:
    #   FLASK_ENV: development
    stdin_open: true
    tty: true
  ### Setup REDIS docker container

  

